
# just a config example. 

SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaWF0IjoxNjIyMzExODA1LCJleHAiOjE5Mzc4ODc4MDV9.il_NbO8i1wCSPXqCss_zztelM2f5o_KtZgIjzgmd4ik'
SUPABASE_URL: 'https://qkacsffiqokwdpkrwpyl.supabase.co'
